feat: added UserController
blackspyek/spring-library-platform pull request #7
Opened 2024-11-15 18:02 UTC by DFraczek

## Features Implemented:

### 1. **UserController Implementation**
   - Added a new `UserController` to manage user-related operations through a RESTful API. This includes endpoints for:
     - **Updating user roles** (`PUT /api/user/roles/{username}`) – Only accessible by ADMIN users.
     - **Fetching user information by username** (`GET /api/user/username/{username}`).
     - **Fetching user information by email** (`GET /api/user/email/{email}`).
     - **Fetching user information by user ID** (`GET /api/user/id/{id}`).
     - **Deleting a user by ID** (`DELETE /api/user/{id}`) – Only accessible by ADMIN users.

### 2. **Book and Movie Unit Tests Fixes**
   - **BookNotFoundException** and **MovieNotFoundException** have been introduced to replace `EntityNotFoundException` for Book and Movie deletion and retrieval operations.

## Changes Summary:
- Created **UserController** to handle user role management and user details retrieval.
- Fixed unit tests to properly handle `BookNotFoundException` and `MovieNotFoundException`.

2024-11-15 22:07 UTC, blackspyek requested changes
^^

2024-11-15 22:07 UTC, blackspyek commented on library/src/main/java/org/pollub/library/user/controller/UserController.java
> +    @PreAuthorize("isAuthenticated()")
"isAuthenticated()")
instead of this
hasRole('LIBRARIAN')

2024-11-15 22:07 UTC, blackspyek commented on library/src/main/java/org/pollub/library/user/controller/UserController.java
> +    @PreAuthorize("isAuthenticated()")
everywhere

2024-11-21 13:22 UTC, DFraczek commented on library/src/main/java/org/pollub/library/user/controller/UserController.java
> +    @PreAuthorize("isAuthenticated()")
fixed

2024-11-21 19:38 UTC, blackspyek approved these changes

2024-11-21 19:38 UTC, blackspyek commented
LGTM

2024-11-22 10:45 UTC, merged